language: python

python:
  - 2.7

services: postgresql

before_install:
  - cd kamaji-api
  - export DJANGO_SETTINGS_MODULE=api.settings.travis
  - export PYTHONPATH=$HOME/builds/fredkj/kamaji
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - cd kamajiapi
  - python manage.py migrate --noinput
