# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-07 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePlaceholder',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='network',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='loadbalancer',
            name='vip_subnet',
        ),
        migrations.RemoveField(
            model_name='overlaysubnet',
            name='network',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='LoadBalancer',
        ),
        migrations.DeleteModel(
            name='OverlayNetwork',
        ),
        migrations.DeleteModel(
            name='OverlaySubnet',
        ),
    ]
